### ISSUE TITLE
Creaking head dropped when heart is broken

### ISSUE THREAD

**Issue by blue-pinapple** [EvModder/DropHeads#129]
Would it be possible for the creaking to make the chance roll when the creaking heart is broken? In the game, this basically kills the creaking.

**Comment by EvModder** [comment]
Ooh, that's very good, I did not realize it triggers EntityDeathEvent.
If that is indeed the case, it should only require adding "`CREAKING: 0.05`" (or any number besides 0.0, the default) to `head-drop-rates.txt`, and it should start working.

I'll go ahead and do that in the default config, and test it myself to make sure it works.

P.S.: Sorry for very late reply

**Comment by blue-pinapple** [comment]
In my testing, it still doesn't seem to be working. 
It works when I summon one in creative a punch it drops a head, but the breaking the heart doesn't.

p.s. I'm still on the beta version and not the one you sent me yesterday

**Comment by EvModder** [comment]
Yeah the version on bukkit/curseforge is not updated yet, only the dev jar on GitHub, I'll post it later today but it usually takes a few hours/days to appear

**Comment by EvModder** [comment]
I made some changes to the default configs, specifically in `entity-settings.yml`:

```
# Whether to drop heads if not killed by a player
drop-for-nonplayer-kills:
  default: false
  creaking: true

# Whether to drop heads if last-damage-cause is not a valid entity
# Instead, any entity damaged by a player within the time threshold is able
# to drop its head. Set threshold <= 0 to allow head drops for any death
drop-for-indirect-kills:
  default: false
  creaking: true
indirect-kill-threshold: '30s'
```

With these settings, Creakings will drop heads properly, despite not being directly killed by a player.
You might need to make these changes in your config file as well, or delete it when you update to DropHeads v3.10.1 so it gives you a fresh default config with the new changes
